//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BatchProcess.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BATCHPROCESS_DIALOG         102
#define IDP_SOCKETS_INIT_FAILED         103
#define ID_INIT_DB_CONNECT              104
#define FAIL_CREATE_RECORD_INSTANCE     105
#define START_LEAD_FILE_READ            106
#define ID_LEADS_COUNT                  107
#define ID_COM_ERR                      108
#define IDR_MAINFRAME                   128
#define IDR_MENUMAIN                    130
#define IDC_LIST_OUTPUT                 1000
#define IDC_BUTTON_READ                 1001
#define IDC_BUTTON_PRINT_LIST           1002
#define IDC_BUTTON_PRINT_INTERNET       1003
#define IDC_CHECK_VERIFIED              1004
#define IDC_BUTTON_TEST                 1005
#define IDC_EDIT_STATES                 1006
#define IDC_STATIC_STATES               1007
#define IDC_BUTTON_TEST_ORDER           1008
#define IDC_EDIT_COMPANYID              1009
#define IDC_EDIT_CONTACT                1010
#define IDC_STATIC_STATES2              1011
#define IDC_EDIT_ORDERID                1012
#define IDC_EDIT_FAXNUMBER              1013
#define IDC_EDIT_QUANTITY               1014
#define IDC_EDIT_EMAIL                  1015
#define IDC_EDIT_AGENT                  1016
#define IDC_EDIT_RATE                   1017
#define IDC_EDIT_ZIP_FILTER             1018
#define IDC_EDIT_DESIRED_LOAN_FILTER    1019
#define IDC_EDIT_AREACODE_FILTER        1020
#define IDC_CHECK_ONEPASS               1021
#define IDC_CHECK_EXCEL                 1022
#define IDC_CHECK_FAX                   1023
#define IDC_CHECK_WORD                  1024
#define IDC_CHECK_ONELEAD               1025
#define IDC_CHECK_EMAILNOTE             1026
#define IDC_EDIT_CASHOUT                1027
#define IDC_EDIT_2NDMORTGAGE            1028
#define IDC_EDIT_DEBTCON                1029
#define IDC_BUTTON_OPEN_INTERNET_ORDERS 1030
#define IDC_CHECK_PRINT                 1031
#define IDC_EDIT_LOOKINGTO              1032
#define IDC_EDIT_LANG                   1033
#define IDC_EDIT_CREDIT                 1034
#define IDC_EDIT_HOMETYPE               1035
#define IDC_EDIT_LOCATION               1036
#define IDC_CHECK_PRIORITY              1037
#define IDC_CHECK_MINI1003              1038
#define IDC_CHECK_ADCAMPAIGN            1039
#define IDC_EDIT_AGENTID                1040
#define IDC_EDIT_SQL                    1041
#define IDC_CHECK_SUBPRIME              1042
#define IDC_BUTTON_OPEN_INTERNET_ONEPASS 1043
#define IDC_EDIT_SFR                    1044
#define IDC_EDIT_MOBILE                 1045
#define IDC_EDIT_COMMERCIAL             1046
#define IDC_EDIT_CITY                   1047
#define IDC_EDIT_LTV                    1048
#define IDC_CHECK_ABOVE                 1049
#define IDC_BUTTON_PROCESS              1050
#define IDC_BUTTON_STOP                 1051
#define IDC_EDIT_LAST_ORDER_QUANTITY    1052
#define IDC_EDIT_LAST_ORDER_QUANTITY2   1053
#define IDC_EDIT_COMPANY_ORDERS_COUNT   1053
#define IDC_STATIC_COMPANY_COUNT_ORDERS 1054
#define IDC_EDIT_YIELD                  1055
#define IDC_STATIC_COMPANY_COUNT_ORDERS2 1056
#define IDC_EDIT_CAMPAIGNID             1057
#define IDC_EDIT_LEADTYPE               1058
#define IDC_EDIT_ORDERTYPE              1059
#define IDC_PROGRESS_READ               1060
#define IDC_BUTTON_VERIFIED             1061
#define IDC_BUTTON_INTERNET             1062
#define IDC_BUTTON_ONEPASS              1063
#define IDC_COMBO_GROUP                 1064
#define IDC_PROGRESS_OVERALL            1065
#define IDC_BUTTON_RETRY                1066
#define IDC_BUTTON_GEN_ORDERS           1067
#define IDC_BUTTON_RETRY2               1068
#define IDC_BUTTON_STATS                1068
#define IDC_COMBO1                      1069
#define IDC_COMBO_STATES                1069
#define S_START_MESSAGE                 2000
#define S_CHAR_MESSAGE                  2001
#define S_END_MESSAGE                   2002
#define CMD_PROCESS                     2003
#define S_ORDER_TRANS                   2004
#define ID_LEAD_READ                    3103
#define S_START_FAX_STRING              4000
#define S_CHAR_FAX                      4001
#define S_END_FAX_STRING                4002
#define S_FAX_SUCCESS                   4003
#define S_FAX_FAIL                      4004
#define S_TIMER_RESET                   4005
#define S_TIMER_START                   4006
#define S_TIMER_FIRE                    4007
#define OB_FAXJOB_START                 4050
#define OB_FAXJOB_END                   4051
#define OB_FAXJOB_ELEMENT               4052
#define OB_FAXJOB_CAMID                 4053
#define OB_FAXJOB_ORDERID               4054
#define OB_FAXJOB_DIV                   4055
#define OB_FAXJOB_AGENTEMAIL_CHAR       4056
#define OB_FAXJOB_AGENTNAME_CHAR        4057
#define OB_FAXJOB_COMPANY_CHAR          4058
#define OB_FAXJOB_CONTACT_CHAR          4059
#define OB_FAXJOB_FAXNUM_CHAR           4060
#define OB_FAXJOB_FILENAME_CHAR         4061
#define OB_FAXJOB_STATES_CHAR           4062
#define OB_FAXJOB_SENDCOVERPAGE         4063
#define PO_VERIFIED                     5000
#define PO_INTERNET                     5001
#define PO_ONEPASS                      5002
#define PO_PRIORITY                     5003
#define PO_SENTZERO                     5004
#define PO_NEWCUSTOMER                  5005
#define PO_NORMAL                       5006
#define PO_DONE                         5007
#define LOG_WRITE_DONE                  5008
#define EMAIL_FAIL_CHAR                 5009
#define EMAIL_FAIL_END                  5010
#define EMAIL_FAIL_START                5011
#define PO_RETRY_SENDING                5012
#define PO_RETRY_SEND_NODOCGEN          5013
#define PO_GEN_ORDERS                   5014
#define PO_POP_CHECK                    5015
#define PO_STATS                        5016
#define PO_AK                           5101
#define PO_AL                           5102
#define PO_AR                           5103
#define PO_AZ                           5104
#define PO_CA                           5105
#define PO_CO                           5106
#define PO_CT                           5107
#define PO_DC                           5108
#define PO_DE                           5109
#define PO_FL                           5110
#define PO_GA                           5111
#define PO_HI                           5112
#define PO_IA                           5113
#define PO_ID                           5114
#define PO_IL                           5115
#define PO_IN                           5116
#define PO_KS                           5117
#define PO_KY                           5118
#define PO_LA                           5119
#define PO_MA                           5120
#define PO_MD                           5121
#define PO_ME                           5122
#define PO_MI                           5123
#define PO_MN                           5124
#define PO_MO                           5125
#define PO_MS                           5126
#define PO_MT                           5127
#define PO_NC                           5128
#define PO_ND                           5129
#define PO_NE                           5130
#define PO_NH                           5131
#define PO_NJ                           5132
#define PO_NM                           5133
#define PO_NV                           5134
#define PO_NY                           5135
#define PO_OH                           5136
#define PO_OK                           5137
#define PO_OR                           5138
#define PO_PA                           5139
#define PO_RI                           5140
#define PO_SC                           5141
#define PO_SD                           5142
#define PO_TN                           5143
#define PO_TX                           5144
#define PO_UT                           5145
#define PO_VA                           5146
#define PO_VT                           5147
#define PO_WA                           5148
#define PO_WI                           5149
#define PO_WV                           5150
#define PO_WY                           5151
#define PO_ALL                          5152
#define ID_PROGRESS                     6000
#define ID_PROGRESS_OVERALL             6001
#define N_MESSAGE                       7500
#define N_START_STRING                  8000
#define N_STOP_STRING                   8001
#define ID_FILE_EXIT                    32771
#define ID_HELP_ABOUT                   32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           207
#endif
#endif
